// Caractères spéciaux d'affiche sur terminal

#ifndef TERMINALCOLOR_H
#define TERMINALCOLOR_H

#define TEXT_RESET "\x1B[0m"
#define TEXT_BOLD "\x1B[1m"
#define TEXT_ITALIC "\x1B[3m"
#define TEXT_LINE "\x1B[K"
#define CLEAR "\x1B[H\x1B[J"

#define COLOR_BLACK "\x1B[30m"
#define COLOR_RED "\x1B[31m"
#define COLOR_GREEN "\x1B[32m"
#define COLOR_YELLOW "\x1B[33m"
#define COLOR_BLUE "\x1B[34m"
#define COLOR_MAGENTA "\x1B[35m"
#define COLOR_CYAN "\x1B[36m"
#define COLOR_WHITE "\x1B[37m"

#define BACKGROUND_BLACK "\x1B[40m"
#define BACKGROUND_RED "\x1B[41m"
#define BACKGROUND_GREEN "\x1B[42m"
#define BACKGROUND_YELLOW "\x1B[43m"
#define BACKGROUND_BLUE "\x1B[44m"
#define BACKGROUND_MAGENTA "\x1B[45m"
#define BACKGROUND_CYAN "\x1B[46m"
#define BACKGROUND_WHITE "\x1B[47m"

#define CATEGORY_BLACK BACKGROUND_BLACK " " TEXT_RESET " "
#define CATEGORY_RED BACKGROUND_RED " " TEXT_RESET " "
#define CATEGORY_GREEN BACKGROUND_GREEN " " TEXT_RESET " "
#define CATEGORY_YELLOW BACKGROUND_YELLOW " " TEXT_RESET " "
#define CATEGORY_BLUE BACKGROUND_BLUE " " TEXT_RESET " "
#define CATEGORY_MAGENTA BACKGROUND_MAGENTA " " TEXT_RESET " "
#define CATEGORY_CYAN BACKGROUND_CYAN " " TEXT_RESET " "
#define CATEGORY_WHITE BACKGROUND_WHITE " " TEXT_RESET " "

#define ERROR CATEGORY_RED COLOR_RED
#define SUCCESS CATEGORY_GREEN COLOR_GREEN
#define INFO CATEGORY_YELLOW COLOR_YELLOW

#endif